// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQ9PltkFY_HU1VGXH9kI8fvAJVFC9ixw',
    appId: '1:339774650349:web:784893ee6dec3177c559e4',
    messagingSenderId: '339774650349',
    projectId: 'azan-5d7de',
    authDomain: 'azan-5d7de.firebaseapp.com',
    storageBucket: 'azan-5d7de.appspot.com',
    measurementId: 'G-C8T9SN95W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRIUU1PfhRBSDb4CVDviSTAW4KnDqWDGs',
    appId: '1:339774650349:android:d8e93f6c01694783c559e4',
    messagingSenderId: '339774650349',
    projectId: 'azan-5d7de',
    storageBucket: 'azan-5d7de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSjMnX3OhxgY31YYWqLBBli-vVrK1P-TM',
    appId: '1:339774650349:ios:5b08ae4ce257c4d7c559e4',
    messagingSenderId: '339774650349',
    projectId: 'azan-5d7de',
    storageBucket: 'azan-5d7de.appspot.com',
    iosBundleId: 'com.example.azan',
  );
}
